name: Landing page builder

on:
  push:
    paths:
      - site/**
    branches:
      - live
      - staging
  workflow_dispatch:

jobs:
  build:
    concurrency: landing-build-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: site
        single-commit: true
